{% set name = "minimalkv" %}
{% set version = "1.9.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/minimalkv-{{ version }}.tar.gz
  sha256: 44b8564d8b01c6bde0eae87b8e23670c4d5c5b808af23e49dcee26060e0491a1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools_scm
  run:
    - python >=3.8
    - uritools
  run_constrained:
    - gcsfs >=2022.10.0

test:
  imports:
    - minimalkv
  commands:
    - pip check
    - python -c 'from minimalkv import get_store; get_store("fs", path=".")'
    - python -c 'from minimalkv import get_store; get_store("hfs", path=".")'
  requires:
    - pip

about:
  home: https://github.com/data-engineering-collective/minimalkv
  summary: A key-value storage for binary data, support many backends.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jtilly
    - fjetter
    - mlondschien
    - siboehm
    - xhochy
